name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.4]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - php-versions: 7.4
          - testbench: 5.*

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: pcov

      - name: Validate Composer files
        run: composer validate

      - name: Install dependencies
        run: composer update ${{ matrix.dependency-version }}  --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Check for style violations
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run test suite
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: "Send code coverage report to Codecov.io"
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        run: "bash <(curl -s https://codecov.io/bash) || true"

